---
- name: Full Jetson Setup with uv, MQTT, YOLO and Script Execution
  hosts: jetson
  become: yes
  gather_facts: no

  vars:
    do_reboot: false

  tasks:
    - name: Reboot the machine (if user says yes)
      reboot:
        reboot_timeout: 600
        test_command: whoami
      when: do_reboot | bool
    
    
    - name: Wait for system to come back online (only if rebooted)
      wait_for_connection:
        timeout: 300
      when: do_reboot | bool  
    
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install core dependencies
      apt:
        name:
          - git
          - python3-pip
          - python3-venv
          - libopencv-dev
          - mosquitto
          - mosquitto-clients
        state: present

    - name: Enable and start mosquitto service
      systemd:
        name: mosquitto
        enabled: yes
        state: started

    - name: Allow anonymous MQTT access (for dev only)
      copy:
        dest: /etc/mosquitto/conf.d/allow-anonymous.conf
        content: |
          listener 1883
          allow_anonymous true
      notify:
        - Restart Mosquitto

    - name: Install uv globally via pip with break-system-packages
      pip:
        name: uv
        executable: pip3
        extra_args: --break-system-packages
      become: yes

    - name: Clone YOLO project
      git:
        repo: 'https://github.com/prakhar105/object-detection.git'
        dest: /home/alex/yolo
        version: main

    - name: Create uv virtual environment
      command: uv venv
      args:
        chdir: /home/alex/yolo
      environment:
        UV_VENV_PATH: /home/alex/yolo/.venv

    - name: Sync dependencies with uv pip sync
      command: uv pip sync requirements.txt
      args:
        chdir: /home/alex/yolo
      environment:
        UV_VENV_PATH: /home/alex/yolo/.venv

    - name: Install yt-dlp using uv
      command: uv pip install yt-dlp supervision
      args:
        chdir: /home/alex/yolo
      environment:
        UV_VENV_PATH: /home/alex/yolo/.venv

    - name: Run YOLO script
      command: /home/alex/yolo/.venv/bin/python scripts/realtime_video_detect_mqtt_prometheus_client.py --ip 
      args:
        chdir: /home/alex/yolo

  handlers:
    - name: Restart Mosquitto
      systemd:
        name: mosquitto
        state: restarted